<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Robert Camacho" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../blog/">BLOG</a></li>
        
        <li><a href="../projects/">PROJECTS</a></li>
        
        <li><a href="../resume1.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          May 1, 2020
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 5/1/2020. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>The dataset I found was the Faithfulfaces in the Stat2data library. This dataset consists of college students as they were asked to look at a photograph of an opposite-sex adult face and to rate the person, on a scale from 1 (low) to 10 (high), for attractiveness. They were also asked to rate trustworthiness, faithfulness, and sexual dimorphism (i.e., how masculine a male face is and how feminine a female face is). Overall, 68 students (34 males and 34 females) rated 170 faces (88 men and 82 women). This dataset consists of 7 variables and 170 observations. The SexDimorph variable measures the rating of sexual dimorphism (masculinity for males, femininity for females). The attract variable is the rating of attractiveness. The cheater variable is a variable that measured if the face subject was unfaihtful to the partner and it was rated using a 1=yes and a 0=no. The trust variable was rating the trustworthiness. The Faithful variable was the faithfulness. Lastly, the Ratersex variable showed the sex of the rater (F=female or M=male).</p>
</div>
<div id="manova-testing" class="section level2">
<h2>MANOVA Testing</h2>
<pre class="r"><code>library(Stat2Data)
data(FaithfulFaces)
?FaithfulFaces
man_faith &lt;- manova(cbind(SexDimorph,Attract,Trust,Faithful)~FaceSex,data=FaithfulFaces)
summary(man_faith)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## FaceSex 1 0.20961 10.939 4 165 6.827e-08 ***
## Residuals 168
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man_faith)</code></pre>
<pre><code>## Response SexDimorph :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 12.36 12.3598 13.885 0.0002652 ***
## Residuals 168 149.55 0.8902
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Attract :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 0.363 0.36264 0.4798 0.4895
## Residuals 168 126.982 0.75584
##
## Response Trust :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 2.314 2.31372 3.7592 0.05419 .
## Residuals 168 103.401 0.61548
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Faithful :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 27.229 27.2293 35.823 1.27e-08 ***
## Residuals 168 127.698 0.7601
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(FaithfulFaces$Faithful,FaithfulFaces$FaceSex,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  FaithfulFaces$Faithful and FaithfulFaces$FaceSex 
## 
##   F      
## M 1.3e-08
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(FaithfulFaces$Trust,FaithfulFaces$FaceSex,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  FaithfulFaces$Trust and FaithfulFaces$FaceSex 
## 
##   F    
## M 0.054
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1-(.95)^16</code></pre>
<pre><code>## [1] 0.5598733</code></pre>
<pre class="r"><code>.05/16</code></pre>
<pre><code>## [1] 0.003125</code></pre>
<p><em>I ran a MANOVA test to evaluate to see if SexDimorph, attractfulness, trustfulness, and faithfulness had a mean difference against FaceSex. In running the test, there was a p-value present that was well below 0.05 and was 6.827e-08. After running the MANOVA test, an ANOVA was conduct to evaluate and see which variables had a mean difference. Only SexDimorph, Trust, and Faithful were the only variables that contained a mean difference while the variable Attract did not as it had a p-value of 0.4895 and the other p-values were below 0.05. Following the anova, a pairwise t test was perfomred for the varibales SexDimorph, Trust, and Faithful since they were the only variables that displayed a mean difference in the anova test. The pairwise t-test showed that all of those specific variables depicted a difference between males and females, as they were below 0.05.</em></p>
</div>
<div id="randomized-testing" class="section level2">
<h2>Randomized Testing</h2>
<pre class="r"><code>FaithfulFaces%&gt;%group_by(FaceSex)%&gt;%summarize(mean_face=mean(Trust))</code></pre>
<pre><code>## # A tibble: 2 x 2
##   FaceSex mean_face
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 F            4.44
## 2 M            4.21</code></pre>
<pre class="r"><code>4.444061-4.210591</code></pre>
<pre><code>## [1] 0.23347</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
  Faith&lt;-data.frame(sex=sample(FaithfulFaces$FaceSex),Trust=FaithfulFaces$Trust)
  rand_dist[i]&lt;-mean(Faith[Faith$sex==&quot;F&quot;,]$Trust)-
  mean(Faith[Faith$sex==&quot;M&quot;,]$Trust)}
mean(rand_dist&gt;0.23347)*2</code></pre>
<pre><code>## [1] 0.054</code></pre>
<pre class="r"><code>{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;);abline(v=0.23347,col=&quot;red&quot;)}</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><em>Utilizing the randomized test, the test gathered a sample of FaceSex and pulled it 5,000 times and then evaluated the mean of both sexes from the Trust variable and subtracted them to find the difference. After running a randomized test, the p-value of a two-tailed test was less than 0.05, as it was 0.0564. The histogram was then displayed to show the null distribution and test statistic. The null hypothesis is that there is no difference in the Trust varibale in males and females. The alternative hypothesis is that there is a difference in the Trust varibale in males and females. In evaluation of the randomized test and the p-value, we can reject the null hypothesis.</em></p>
</div>
<div id="linear-regression" class="section level2">
<h2>Linear Regression</h2>
<pre class="r"><code>library(sandwich)
library(lmtest)
fit &lt;- lm(Attract~Trust*FaceSex, data=FaithfulFaces)
coef(fit)</code></pre>
<pre><code>## (Intercept) Trust FaceSexM Trust:FaceSexM
## 1.3648789 0.3555250 -0.2845297 0.1092399</code></pre>
<pre class="r"><code>ggplot(fit, aes(x=Trust, y=Attract, color = FaceSex)) +
    geom_point(shape=1) +
    geom_smooth(method=lm,se=FALSE)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-3-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_qq(aes(sample=resids))+geom_qq_line()</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-3-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>summary(fit)$coef[,1:2] #uncorrected</code></pre>
<pre><code>##                  Estimate Std. Error
## (Intercept)     1.3648789  0.5459844
## Trust           0.3555250  0.1212013
## FaceSexM       -0.2845297  0.7090092
## Trust:FaceSexM  0.1092399  0.1606560</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))[,1:2] #corrected</code></pre>
<pre><code>##                  Estimate Std. Error
## (Intercept)     1.3648789  0.7469485
## Trust           0.3555250  0.1710796
## FaceSexM       -0.2845297  0.8565108
## Trust:FaceSexM  0.1092399  0.1969627</code></pre>
<p><em>After running a linear regression, the coefficent estimates for Trust was 0.355250, FaceSex for males was -0.2845297, and the Trust:FaceSex M was 0.1092399. A plot of Trust vs Attract in males and females was perfomred and from observation of the graph, there seemed to be a higher interaction in males than in females. Assumptions were analyzed, and everything was observed to be normal.</em></p>
</div>
<div id="bootstrapping-standard-error" class="section level2">
<h2>Bootstrapping Standard Error</h2>
<pre class="r"><code>boot_face&lt;-FaithfulFaces[sample(nrow(FaithfulFaces),replace=TRUE),]
samp_distn&lt;-replicate(5000, {
  boot_face&lt;-FaithfulFaces[sample(nrow(FaithfulFaces),replace=TRUE),]
  fit2&lt;-lm(Attract~Trust*FaceSex,data=FaithfulFaces)
  coef(fit2)
})
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) Trust FaceSexM Trust:FaceSexM
## 1           0     0        0              0</code></pre>
</div>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<pre class="r"><code>fit2&lt;-glm(Cheater~Attract+Trust+Faithful, data=FaithfulFaces, family=&quot;binomial&quot;)
coeftest(fit2)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  0.88845    1.26872  0.7003   0.4838
## Attract     -0.18216    0.25986 -0.7010   0.4833
## Trust        0.11510    0.31059  0.3706   0.7109
## Faithful    -0.33650    0.24842 -1.3545   0.1756</code></pre>
<pre class="r"><code>#confusion matrix
prob &lt;- predict(fit2,type=&quot;response&quot;)
table(predict=as.numeric(prob&gt;.5),truth=FaithfulFaces$Cheater)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0   120  50 170
##     Sum 120  50 170</code></pre>
<pre class="r"><code>class_diag&lt;-function(prob,truth){ 
  tab&lt;-table(factor(prob&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2] 
  spec=tab[1,1]/colSums(tab)[1] 
  ppv=tab[2,2]/rowSums(tab)[2]
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1

  ord&lt;-order(prob, decreasing=TRUE)
  prob &lt;- prob[ord]; truth &lt;- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup&lt;-c(prob[-1]&gt;=prob[-length(prob)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  data.frame(acc,sens,spec,ppv,auc)
}

library(plotROC)
RocPlot &lt;- ggplot(FaithfulFaces)+geom_roc(aes(d=Cheater,m=prob),n.cut=0)
RocPlot</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(RocPlot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5633333</code></pre>
<pre class="r"><code>#10-fold
set.seed(1234)
k=10

data1&lt;-FaithfulFaces[sample(nrow(FaithfulFaces)),] 
folds&lt;-cut(seq(1:nrow(FaithfulFaces)),breaks=k,labels=FALSE)  
diags&lt;-NULL
for(i in 1:k){
  train&lt;-data1[folds!=i,]
  test&lt;-data1[folds==i,]
  truth&lt;-test$Cheater

  fit3&lt;-glm(Cheater~.,data=FaithfulFaces,family=&quot;binomial&quot;)
  probs2&lt;-predict(fit3,newdata = test,type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs2,truth))
}
apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.7000000 0.0000000 0.9909091       NaN 0.6036863</code></pre>
<p><em>A logistic regression was performed and in this occurence, the intercepts depict the interactions of attractfullness and trustfulness in a cheater. The intercept for attract was -0.18216, the intercept for trust was 0.11510, and the intercept for faithful was -0.33650. The accuracy, which was 0.7058824, sensitivity, which was 0, specificity, which was 1, and the auc, which was 0.5633333, were all computed. The auc is not as good since it is so low. Following the running of the 10-fold, the auc seemed to remain the same and there was no difference.</em></p>
</div>
<div id="lasso" class="section level2">
<h2>LASSO</h2>
<pre class="r"><code>library(glmnet)
x &lt;- model.matrix(fit)[,-1]
y&lt;-as.matrix(FaithfulFaces$Cheater)
cv&lt;-cv.glmnet(x,y,family=&#39;binomial&#39;)
lasso1&lt;-glmnet(x,y,family=&#39;binomial&#39;,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 4 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)    -0.8754687
## Trust           0.0000000
## FaceSexM        .        
## Trust:FaceSexM  .</code></pre>
<pre class="r"><code>set.seed(1234)
k=10

data2&lt;-FaithfulFaces[sample(nrow(FaithfulFaces)),]
folds&lt;-cut(seq(1:nrow(FaithfulFaces)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){ 
  train2&lt;-data2[folds!=i,]  
  test2&lt;-data2[folds==i,] 
  truth2&lt;-test2$Cheater
  probs3&lt;- predict(fit,newdata=test2, type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs3,truth2))
}

apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.2941176 1.0000000 0.0000000 0.2941176 0.4573660</code></pre>
<p><em>A lasso regression was performed and the observnace of the auc was lower than the one that was calculated in the logistic regression. The auc in the lasso regression is 0.4573660 and the auc in the logistic regression was above 0.50 and after running the 10-fold as well, and it seemed that the accuracy was not as high when running the logistic regression.</em></p>
</div>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../js/docs.min.js"></script>
<script src="../js/main.js"></script>

<script src="../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
